### ISSUE TITLE
Merge worlds ordering bug

### ISSUE THREAD

**Issue by guybedford** [bytecodealliance/wasm-tools#1122] opened 2023-07-13 18:44 UTC
I managed to hit some errors when building a component using a world created via `merge_worlds`.

The WIT is the following:

```wit
package local:virt

world virtual-base {
  import console: interface {
    log: func(msg: string) -> ()
  }
}

world virtual-env {
  import wasi:cli-base/environment
  export wasi:cli-base/environment
}

world virtual-fs {
  import wasi:cli-base/preopens
  import wasi:filesystem/filesystem
  import wasi:io/streams
  export wasi:io/streams
  export wasi:filesystem/filesystem
  export wasi:cli-base/preopens
}
```

The merge is then `merge_worlds` applied for merging `virtual-fs` into `virtual-base` and creating a component to that merged world.

If the WIT is manually reordered to:

```wit
package local:virt

world virtual-base {
  import console: interface {
    log: func(msg: string) -> ()
  }
}

world virtual-env {
  import wasi:cli-base/environment
  export wasi:cli-base/environment
}

world virtual-fs {
  import wasi:cli-base/preopens
  import wasi:filesystem/filesystem
  import wasi:io/streams
  export wasi:io/streams
  export wasi:filesystem/filesystem
  export wasi:cli-base/preopens
}
```

Then the issue is fully resolved.

The line triggering the error is the following in `process_exports_used`:

```rs
if set.insert(other) && self.exports_used.contains_key(&other) {
  set.extend(self.exports_used[&other].iter().copied());
}
```

where `exports_used` does not contain `other` when `other` is `wasi:filesystem/filesystem`.

A full replication can be found at https://github.com/bytecodealliance/WASI-Virt/tree/merge-worlds-bug triggered by `cargo test`.

**Comment by alexcrichton** [comment] 2023-07-14 18:35
Ok after tracking this down I believe the issue is that the `virtual_adapter.wasm` is built with wit-component 0.11 where the processing elsewhere happens with wit-component 0.12. From that branch if I run `cargo +nightly update -p wit-bindgen` then the tests get beyond the panic mentioned in this issue.

This is somewhat expected where wit-component expects that a `Resolve` is valid and fully elaborated, and so 0.11 to 0.12 was a breaking change in the sense that a fully elaborated resolve changed (order between fields and such). That's not exactly an expected way that things were going to break, and it's definitely something to keep in mind for the future, but I don't think there's a great way to fix this for now.

In that case I'm going to close this since the fix is easy enough for now (updating deps) and a deeper fix may not be necessary into the future. I still think it's worth keeping eyes peeled for issues like this if it crops up again.

**Closed by alexcrichton** 2023-07-14 18:35 UTC

**Comment by guybedford** [comment] 2023-07-14 18:53
Wow, apologies for the noise on this - I was under the impression that all git refs were to latest. Thanks again for your help!

**Comment by alexcrichton** [comment] 2023-07-14 19:19
No worries! This was a surprising, but important, consequence that I was previously unaware of so still definitely worth it to track down
